### PR TITLE
Create a card for Aimee

### PR DESCRIPTION
**Pull request by aimeetacchi**

### CODE REVIEW

**Comment by SiAdcock** [comment]
Congrats, @darkxangel84, on your first WDOTS PR! 🎉 

I have two comments, hopefully really quick to change

By moving those `<div class="speaker">` statements down onto separate lines, it has broken the layout on iPad:

**Before:**
screen shot 2017-03-05 at 20 19 04

**After:**
screen shot 2017-03-05 at 20 20 23

This is because the whitespace characters between the `</div>` and `<div class="speaker">` is significant. Removing the whitespace restores the layout.

Also can you reduce the image size of `src/img/aimee-130.jpg` so it is 130px x 130px?

Thanks for all your hard work so far 💎

**Comment by Jameskmonger** [comment]
@SiAdcock I do feel that maybe we should work on removing the reliance on whitespace. Obviously keep it as-is for now,  but look into fixing it in a future PR.

**Comment by aimeetacchi** [comment]
@SiAdcock Thanks!!! :D Sure thing I'll fix that tomorrow when I get home! it was a good experience!

**Comment by SiAdcock** [comment]
Awesome, thanks @darkxangel84, I've learned a lot too 😄 

@Jameskmonger Good shout. I've raised an issue #121

**Review by SiAdcock — APPROVED** [review]
Amazing! Thanks Aimee 💎 💎 💎 👍

**Comment by SiAdcock** [comment]
This also fixes #116

**Comment by aimeetacchi** [comment]
Thanks @SiAdcock

**Pull request merged**
