### PR TITLE
Remove height/width from footer WDOTS SVG

### PR DESCRIPTION
**Pull request by crgeary**
## What does this change?

The `height` and `width` attributes have been removed from the SVG used for the WDOTS logo (in the footer).

## What is the benefit?

See: #123 

The problem is the `height` and `width` properties do not implicitly set the aspect ratio like they would do on an image. Explained in this [css-tricks article on SVGs](https://css-tricks.com/scale-svg/#article-header-id-2). It seems these properties are almost useless, and removing them does appear to the fix the scaling issue in Safari.

## Screenshots

footer in safari

### CODE REVIEW

**Review by SiAdcock — APPROVED** [review]
Nice tip, looks good dude

**Comment by SiAdcock** [comment]
If `height` and `width` are next to useless, I wonder if it would be worth removing these attributes from all our SVGs? Perhaps something we can explore in a separate PR.

**Comment by crgeary** [comment]
I thought about removing them all, but I'm no front-end whizz. Didn't want to get carried away to then find I've destroyed everything for some poor soul on a blackberry 😂

**Comment by crgeary** [comment]
Also, we could probably solve both this and #104 together.. If we can remove the attributes during the inline that would probably be best.

**Pull request merged**
