### PR TITLE
Compress images

### PR DESCRIPTION
**Pull request by SiAdcock**
# What does this change?

Further compresses a bunch of images, including the mighty [woods.jpg](https://github.com/WDOTS/wdots.github.io/blob/b3c53b53507a9e6d4e5847d22c1d5a29d4c94a49/src/img/woods.jpg)

# What is the point?

Saves about 148.5KB 🚀 🚤 🐎

### CODE REVIEW

**Comment by crgeary** [comment]
What did you use for the image compression? Also, I added some extra images to be compressed.

**Review by crgeary — APPROVED** [review]

**Comment by SiAdcock** [comment]
Nice one, thanks Chris!

Google PageSpeed Insights automatically optimises files that it thinks are too big and zips them up, so I used the images that it generated. It might not be the best solution. What did you use?

**Comment by crgeary** [comment]
I used [TinyPNG](https://tinypng.com) (PNG/JPG) .. I ran the ones you compressed through it, out of curiosity to see the difference, and the panda reckons it can make them even smaller 😮  🐼 

screen shot 2016-12-24 at 12 57 28

**Comment by SiAdcock** [comment]
Whoa! Always trust in the panda 🐼 Every kilobyte helps!

Would you mind compressing those images and adding them to this PR? I will hold you forever in my gratitude! 🙇

**Comment by crgeary** [comment]
All compressed for you!

**Comment by SiAdcock** [comment]
Amazing, thanks @chrisgeary92!

**Pull request merged**
