### PR TITLE
Reuse inline SVGs

### LINKED ISSUE #104: Load repeated SVGs once
screen shot 2017-01-28 at 17 25 04

The social SVGs are inlined multiple times on the page, leading to a lot of unnecessary HTML repetition. It would be good to find a way of loading these only once (preferably inlining them), and [linking to them with a `<use>` element](https://css-tricks.com/svg-use-with-external-reference-take-2/) wherever they are used.

I'm not sure how this approach will interact with the `gulp-inline` plugin that we are using to inline our SVGs.

### PR DESCRIPTION
**Pull request by SiAdcock**
## What does this change?

Currently the way we are inlining SVGs is inefficient. If an SVG is included multiple times in the page, it is inlined multiple times, bloating the critical `index.html` size.

This change consolidates all our individual SVGs into a single SVG. This is inlined and then referenced where it is needed using `<use>` tags.

## What is the benefit?

⬇️  Smaller `index.html` means less data for our users to download 

Fixes #104

### CODE REVIEW

**Comment by SiAdcock** [comment]
This build is generating output HTML of 84KB (~35KB gzipped), whereas currently in production the output is 89KB (~28KB gzipped). This seems to indicate that gzip is better at compressing the HTML with the inlined-in-place SVGs than the HTML containing the SVG symbol library! 

Currently I'm not minifying the SVG symbol library, so that might reduce the weight slightly. I'm going to do some benchmarking to see what a difference this makes to HTML parse and render time.

For now, please don't merge this. Feel free to offer suggestions or have a play with it and let me know if I'm missing something 😅

**Comment by crgeary** [comment]
GZIP compression works by looking for common patterns in your code which it then aliases.. So, thinking about it, all of the Github icons are the same, so GZIP will essentially alias the rest. This is why GZIP is more effective with code than binary files. I expected this approach to still be smaller though.

I've been meaning to experiment with GZIP by ordering attributes in such a way that bigger chunks of HTML match (or can be aliased).

**Comment by SiAdcock** [comment]
@chrisgeary92 Indeed. I wonder if that's some new HTML best practice waiting to emerge: optimisation for gzip. Perhaps it has already emerged and I don't know about it!

Yeah, I totally expected this approach to be smaller. Perhaps I'll tinker with it a bit more then just ship it and see what happens. There's no other way to test in a production-like environment as it's difficult to replicate the production environment locally.

**Comment by crgeary** [comment]
Did some googling and found this:
 - https://manu.ninja/inline-svg-how-i-learned-to-stop-worrying-and-love-gzip

Author stumbled upon the same thing you've just discovered. When you think about what we've done, it's basically add extra code.. GZIP dealt with removing duplicates (kinda), and we just added more code to try and do that which now means all those `<use>` statements are "extra" as far as GZIP is concerned, so it cannot make it smaller.

In light of these findings, I reckon the old method is probably the best way (at least, currently).

**Comment by SiAdcock** [comment]
Closing, as it does not reduce page weight as intended

**Pull request closed without merging**
