### PR TITLE
Meetup Jan 2017

### PR DESCRIPTION
**Pull request by SiAdcock**
Adds meetup description for January 2017

### CODE REVIEW

**Review by crgeary — APPROVED** [review]

**Review by crgeary — CHANGES_REQUESTED** [review]
'non-alcholhic' is wrong (i think, my spelling is bad), should be 'non-alcoholic'

**Comment by SiAdcock** [comment]
Nice, spot, dude, now fixed!

You can add inline comments by going to to the Files Changed tab, hovering your mouse over the erroneous line and clicking the `+` icon. It makes it easier to see where the problems are.

**Review by jamesryan-dev — APPROVED** [review]

**Comment by crgeary** [comment]
Cool, will do in future. Thanks (:

**Comment by Jameskmonger** [comment]
What if I want an alcoholic beverage but don't want a beer?!

**Comment by SiAdcock** [comment]
@Jameskmonger That's an edge case at best! If we get any reports regarding our lack of non-beer support, we'll rethink 👍

**Comment by Jameskmonger** [comment]
I think we risk alienating a potentially large portion of our userbase if this isn't investigated further.. some analytics in this area would be valuable.

**Comment by SiAdcock** [comment]
That's probably the one thing that's not captured by Google Analytics. Perhaps we can add a popup or something that allows people to suggest their drink of choice if it's missing?

**Pull request merged**
